### ISSUE TITLE
ac-source-symbols occurs error when I type "ba"

### ISSUE THREAD

**Issue by jidaikobo-shibata** [auto-complete/auto-complete#423] opened 2015-11-28 06:33 UTC
I added ac-source-symbols to ac-sources.

```lisp
(setq-default ac-sources '(ac-source-words-in-same-mode-buffers ac-source-symbols))
```

and I type "ba" then,

    Error running timer `ac-show-menu': (wrong-type-argument number-or-marker-p \.\.\.)
    Error running timer `ac-update-greedy': (wrong-type-argument number-or-marker-p \.\.\.)

It occurs only when I type "ba". In other pair of alphabets (of I tried) won't occur errors.

I'm using below version

- auto-complete-20151112.2030
- popup-20151125.542

Thanks.

**Comment by syohex** [comment] 2015-11-30 07:21
Which emacs version do you use ?

**Comment by jidaikobo-shibata** [comment] 2015-11-30 07:46
Thank you for giving me an answer.
My Emacs version is below.

GNU Emacs 24.5.1 (x86_64-apple-darwin14.5.0, Carbon Version 157 AppKit 1348.17)

**Comment by syohex** [comment] 2015-11-30 07:57
I have confirmed similar issue on development Emacs version(however it was already fixed in master branch) and this is reproducible issue. However I cannot reproduce this issue on stable version Emacs like 24.5,

![auto-complete](https://cloud.githubusercontent.com/assets/554281/11466289/2fc3d2ba-9783-11e5-8c79-c99a68055390.gif)

Did you install auto-complete package with other Emacs version ? If so, please reinstall auto-complete package. (byte-compiled files which compiled by other Emacs causes similar issue)

**Comment by jidaikobo-shibata** [comment] 2015-11-30 10:29
> Did you install auto-complete package with other Emacs version ? If so, please reinstall auto-complete package.

No. I installed it with this version. But I tried. And unfortunately, it didn't work well. :-(

Suspicious fact exists at my environment. My Emacs.app is complied by myself.
so, maybe this issue is rare case and it should not use time.

Thank you for taking time for me.
I love auto-complete.

many thanks.

**Closed** 2015-12-03 06:55 UTC

**Comment by jidaikobo-shibata** [comment] 2016-01-29 07:41
After this issue, I rebuild my Emacs with emacs-mac-patch.5.15.
ftp://ftp.math.s.chiba-u.ac.jp/emacs/emacs-24.5-mac-5.15.tar.gz

then auto-complete recovered.

This is just a report. Please forget about answering.

thanks.
